baseURL = 'https://awatts.us/'
languageCode = 'en-us'
title = 'Andrew Watts'
theme = 'ananke'

[services.disqus]
  shortname = 'https-awatts-us'

[params]
    author = "Andrew Watts"
    # site_logo = "TRY TO MAKE A LOGO TO GO IN THE UPPER LEFT CORNER"
    background_color_class = "bg-dark-green"

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
    #"mastodon",
    "bluesky",
    "threads",
    "github",
    "rss"
  ]

[parms.ananke.social.mastodon]
username = "@awatts"
profile = "https://universeodon.com/%s"
profilelink = "https://universeodon.com/@awatts"

[params.ananke.social.bluesky]
username = "awatts"
profilelink = "https://bsky.app/profile/awatts.bsky.social"

[params.ananke.social.threads]
username = "@andrewlwatts"
profilelink = "https://www.threads.net/@andrewlwatts"

[params.ananke.social.github]
username = "awatts"
profilelink = "https://github.com/awatts"

[params.ananke.social.rss]
profilelink = "/index.xml"

[[ananke.social.networks]]
slug = "threads"
label = "Threads"
icon = "threads"
profile = "https://www.threads.net/%s"
link = "https://www.threads.net/"
color = "black"
[ananke.social.networks.particles]
text = "permalink"
