baseURL = 'https://awatts.us/'
languageCode = 'en-us'
title = 'Andrew Watts'
theme = 'ananke'

[services.disqus]
  shortname = 'https-awatts-us'

[params]
    author = "Andrew Watts"
    # site_logo = "TRY TO MAKE A LOGO TO GO IN THE UPPER LEFT CORNER"
    background_color_class = "bg-dark-green"

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "mastodon",
  "bluesky",
  "threads",
  "github",
  "rss"
]

[ananke.social.mastodon]
profile = "https://universeodon.com/%s"
username = "@awatts"
profilelink = "https://universeodon.com/@awatts"

[params.ananke.social.bluesky]
label = "BlueSky"
slug = "bluesky"
profilelink = "https://bsky.app/profile/awatts.bsky.social"
color = "#2274f0"

[params.ananke.social.threads]
slug = "threads"
icon = "threads"
label = "Threads"
username = "@andrewlwatts"
profile = "https://www.threads.net/%s"
link = "https://www.threads.net/"
color = "black"

[params.ananke.social.github]
username = "awatts"
profilelink = "https://github.com/awatts"

[params.ananke.social.rss]
profilelink = "/index.xml"
